plugins:
  - jekyll-feed
  - jekyll-environment-variables
  - jekyll-contentful-data-import
  - jekyll-sitemap
  - jekyll-seo-tag

contentful:
  spaces:
    - config:
        lambda_form_contact: ENV_LAMBDA_FORM_CONTACT
        aws_region: ENV_AWS_REGION
        identity_pool_id:  ENV_IDENTITY_POOL_ID
        s3_bucket: ENV_S3_BUCKET