version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo BASE_URL=https://0x4447.com >> .env
      - echo AWS_REGION=$AWS_REGION >> .env
      - echo IDENTITY_POOL_ID=$IDENTITY_POOL_ID >> .env
      - echo NODE_ENV=production >> .env
      - npm install
      - npm run generate
  pre_build:
    commands:
      - aws s3 sync --delete ./dist s3://$S3_BUCKET
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
