version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm run copy
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - '_output/**/*'
  base-directory: '0x4447-com/_output'