version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm i -g @0x4447/avocado
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - avocado -s .
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 cp _output s3://0x4447.com --recursive
      - echo Build completed on `date`
