version: 0.2

env:
  parameter-store:
    ACCESS_KEY: "access_key"
    SECRET_ACCESS_KEY: "secret_access_key"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm i -g git://github.com/0x4447/0x4447-cli-node-avocado.git#development
      - npm i -g @0x4447/potato
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ls -la _input
      - avocado -s .
      - ls -la _input
      - ls -la _output
  post_build:
    commands:
      - echo Entered the post_build phase...
      - potato -s _output -u -b 0x4447.com --access_key $ACCESS_KEY --secret_key $SECRET_ACCESS_KEY
      - echo Build completed on `date`
